app:
  name: orderservice
  server:
    port: 7000
  log:
    level: INFO
  metrics:
    port: 7000

server:
  port: ${app.server.port}
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/order_database
    username: admin
    password: admin123

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operations-sorter: method
    path: /docs
    enabled: true
  packages-to-scan: com.mba.orderservice.infrastructure.adapter.in.rest