networks:
  mynetwork:
    driver: bridge


services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: orders_database
    networks:
      - mynetwork

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - mynetwork

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    expose:
      - "9092"
    networks:
      - mynetwork

  notification:
    image: karlanascimento/notification-service-worker:latest
    container_name: notification-service
    depends_on:
      - kafka
    networks:
      - mynetwork

  order-service:
    image: phfontess/pastry-order-service:latest
    container_name: order-service
    depends_on:
      - postgres
      - kafka
    ports:
      - "7000:7000"
    expose:
      - "7000"
    links:
      - postgres
    networks:
      - mynetwork

  pastry-interface:
    image: victor0777/web-pastry-service:v9
    container_name: web-pastry-service-interface
    ports:
      - "5173:80"
    depends_on:
      - order-service
    networks:
      - mynetwork