name: CI pipeline
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      - name: Verify Docker Compose installation
        run: docker-compose --version
      - name: Start PostgreSQL with Docker Compose
        run: |
          docker-compose -f docker/docker-compose.yaml up -d
        working-directory: docker
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Run Tests
        run: ./gradlew test
      - name: Start Spring Boot Application
        run: ./gradlew bootRun
      - name: Stop Docker Compose
        if: always()
        run: |
          docker-compose -f docker/docker-compose.yaml down
        working-directory: docker